# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['gui.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('testExport.XML', '.'),
        ('MODEL_Logo_M.png', '.'),
        ('model_logo.ico', '.'),
        ('fonts/DejaVuSans.ttf', 'fonts'),
        ('fonts/DejaVuSans-Bold.ttf', 'fonts'),
    ],
    hiddenimports=[
        'ttkbootstrap',
        'ttkbootstrap.constants',
        'matplotlib',
        'matplotlib.backends.backend_tkagg',
        'matplotlib.figure',
        'reportlab',
        'reportlab.platypus',
        'reportlab.platypus.flowables',
        'reportlab.lib.pagesizes',
        'reportlab.lib.styles',
        'reportlab.lib.units',
        'reportlab.lib.colors',
        'reportlab.lib.enums',
        'reportlab.pdfbase',
        'reportlab.pdfbase.pdfmetrics',
        'reportlab.pdfbase.ttfonts',
        'reportlab.pdfgen',
        'reportlab.pdfgen.canvas',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
    collect_all=['reportlab'],
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='DatabazeBarevu',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='model_logo.ico',
)
